server:
  port: 9000
  
#spring:
#    servlet: 
#        multipart:
#           enabled: true
#           max-file-size: 20MB
#           max-request-size: 200MB

spring:
  thymeleaf:
    prefix: classpath:/templates/
    #suffix: .html
  http: 
    multipart:
      max-file-size: 1000Mb
      max-request-size: 1000Mb